PORTFOLIO/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='app_home'
urlpatterns = [
    path('', views.index),
    path('about/', include('about.urls')),
    path('education/', include('education.urls')),
    path('skill/', include('skill.urls')),
    path('projects/', include('projects.urls')),
    path('services/', include('services.urls')),
    path('contact/', include('contact.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import indexView

app_name = 'app_about'

urlpatterns = [
    path('', indexView.as_view(), name='about')
]

projects/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app_projects'

urlpatterns = [
    path('page-<int:page>/', views.indexView.as_view(), name='projects_page'),
    path('category-<str:category>/',
         views.indexView.as_view(), name='projects_category'),
    path('', views.indexView.as_view(), name='projects'),
    path('detail-<slug:slug>', views.detailProjectView.as_view(),
         name='detail_ProjectView'),
    path('report_project/<slug:proyek_slug>/',
         views.report_project, name='report_project'),
]

projects/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.


class Proyek(models.Model):
    ITEM_CHOICES = [
        ('SQL', 'SQL'),
        ('Power BI', 'Power BI'),
        ('Tableau', 'Tableau'),
        ('Python Dash', 'Python Dash'),
        ('Python Django', 'Python Django'),
    ]
    nama = models.CharField(max_length=50)
    category = models.CharField(choices=ITEM_CHOICES)
    gambar = models.ImageField(upload_to='media', blank=True, null=False)
    gambar2 = models.ImageField(upload_to='media', blank=True, null=False)
    gambar3 = models.ImageField(upload_to='media', blank=True, null=False)
    gambar4 = models.ImageField(upload_to='media', blank=True, null=False)
    tanggal = models.DateField(default=timezone.now)
    client = models.CharField(max_length=55)
    output = models.URLField(default='a')
    detail = models.URLField(default='a')
    slug = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.nama)
        super(Proyek, self).save()

    def __str__(self):
        return "{} - {}".format(self.nama, self.category)


class heading(models.Model):
    namaProject = models.OneToOneField(
        Proyek, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.namaProject)

    class Meta:
        abstract = True


class background(heading):
    background = models.TextField()


class dataset(models.Model):
    namaProject = models.ManyToManyField(Proyek, related_name='dataset', )
    heading = models.TextField(blank=True)
    link = models.CharField(max_length=200, blank=True)
    contentLink = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"dataset-{', '.join([str(proyek) for proyek in self.namaProject.all()])}"


class purpose(models.Model):
    namaProject = models.ManyToManyField(Proyek, related_name='purpose')
    isi = models.TextField(blank=True)
    heading = models.TextField(blank=True)

    def __str__(self):
        return f"purpose-{', '.join([str(proyek) for proyek in self.namaProject.all()])}"


class result(models.Model):
    namaProject = models.ManyToManyField(Proyek, related_name='results', )
    isi = models.TextField()
    gambar = models.ImageField(blank=True)
    code = models.TextField(blank=True)

    def __str__(self):
        return f"result-{', '.join([str(proyek) for proyek in self.namaProject.all()])}"


class insight(models.Model):
    namaProject = models.ManyToManyField(Proyek, related_name='insight')
    isi = models.TextField()

    def __str__(self):
        return "{}".format(self.namaProject)


class recommendation(models.Model):
    namaProject = models.ManyToManyField(Proyek, related_name='recomendation')
    isi = models.TextField()

    def __str__(self):
        return "{}".format(self.namaProject)


class dataPrep(models.Model):
    namaProject = models.ManyToManyField(Proyek, related_name='dataprep')
    heading = models.CharField(max_length=200)
    code = models.TextField(blank=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return f"dataprep-{', '.join([str(proyek) for proyek in self.namaProject.all()])}"

projects/views.py
from typing import Any, Dict
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
# Create your views here.
from .models import Proyek


class detailProjectView(DetailView):
    model = Proyek
    extra_context = {
        'title': 'Detail Projects',
    }

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        return super().get_context_data(**kwargs)


class indexView(ListView):
    model = Proyek
    ordering = ['-tanggal']
    paginate_by = 5
    extra_context = {

        'title': 'Projects',
        'item': ['SQL', 'Power BI', 'Tableau', 'Python Dash', 'Python Django']}

    def get_queryset(self):
        category = self.kwargs.get('category')
        if category and category != "ALL":
            return Proyek.objects.filter(category=category)
        return Proyek.objects.all()

    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)


# def index(request):
#     ss = Proyek.objects.all()
#     projec = ss.order_by("-tanggal")
#     context = {
#         'title': 'Projects',
#         'project': projec,
#         'item': ['SQL', 'Power BI', 'Tableau', 'Pyhton Dash', 'Python Django']}

#     return render(request, 'projects/index.html', context)


# def detail_gambar(request, proyek_slug):
#     proyek = get_object_or_404(Proyek, slug=proyek_slug)
#     context = {
#         'title': 'Detail Projects',
#         'proyek': proyek,
#     }

#     return render(request, 'projects/detailProjects.html', context)


def report_project(request, proyek_slug):
    proyek = get_object_or_404(Proyek, slug=proyek_slug)
    context = {
        'title': 'Report Projects',
        'proyek': proyek,
        'orderhead': ['background', 'purpose', 'dataset', 'data preparation', 'result', 'insight and recomendation'],
    }

    return render(request, 'projects/reportProject.html', context)

projects/templates/projects/snippets/buttonProject.html
<div class="button text-center">
  <a href="{% url 'app_projects:report_project' proyek.slug %}" class="btn btn-primary" role="button" aria-pressed="true" target="_blank">Report Project</a>
</div>

projects/templates/projects/snippets/contain-projects.html
<div class="project-information">
  <h4>Project Information</h4>
  <hr />
  <p>Name: {{object.nama}}</p>
  <p>Category : {{object.category}}</p>
  <p>Client : {{object.client}}</p>
  <p>Project Date : {{object.tanggal}}</p>
  <p>Project Dashboard URL : <a href="{{object.output}}">Click here</a></p>
</div>

projects/templates/projects/snippets/menuProject.html
<div class="projects-menu">
  <div class="nav-menu">
    <ul class="nav nav-underline">
      <li class="nav-item"></li>
      <a class="nav-link active" aria-current="page" href="{% url 'app_projects:projects_category' 'ALL' %}" data-category="ALL">ALL</a>
       </li>
      {% for items in item %}
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'app_projects:projects_category' items %}" data-category="{{ items }}">{{ items|upper }}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

projects/templates/projects/snippets/slide-projects.html
<div class="contain-isi-projects">
  <div class="text-start app-title">{{title}}</div>
  <hr />
  <div class="backButton">
    <a href="{% url 'app_projects:projects' %}"><i class="bx bx-home-circle"></i></a>
  </div>
  <div class="row contain-project">
    <div class="col-7 slide-project">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{ proyek.gambar.url }}" class="d-block w-100" alt="First" />
          </div>
          <div class="carousel-item">
            <img src="{{ proyek.gambar2.url }}" class="d-block w-100" alt="Second" />
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="col-4 detail-project">{% include 'projects/snippets/contain-projects.html' %}</div>
  </div>
</div>

projects/templates/projects/snippets/thumbnailProject.html
{% load static %}
<div class="projects-thumbnail">
  <!--- Load images-->
  {% for items in object_list %}
  <!--- Load images-->
  <a href="{% url 'app_projects:detail_ProjectView' items.slug %}">
    <img src="{{ items.gambar.url }}" />
  </a>
  {% endfor %}
</div>
<div class="paginator">
  <div class="leftPaginator">
    {% if is_paginated %} {% if page_obj.has_previous %}
    <a href="{% url 'app_projects:projects_page' page_obj.previous_page_number %}" title=""> &laquo</a>
    {% else %} <span>&laquo</span>
    {% endif %} {% endif %}
  </div>
  <div class="Page">
    {% for item in paginator.page_range %}
    <a href="{% url 'app_projects:projects_page' item %}" title="">{{item}}</a>
    {% endfor %}
  </div>
  <div class="RightPaginator">
    {% if is_paginated %} {% if page_obj.has_next %}
    <a href="{% url 'app_projects:projects_page' page_obj.next_page_number %}" title=""> &raquo</a>
    {% else %} <span>&raquo</span> {% endif %} {% endif %}
  </div>
</div>