PORTFOLIO/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='app_home'
urlpatterns = [
    path('', views.index),
    path('about/', include('about.urls')),
    path('education/', include('education.urls')),
    path('skill/', include('skill.urls')),
    path('projects/', include('projects.urls')),
    path('services/', include('services.urls')),
    path('contact/', include('contact.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import indexView

app_name = 'app_about'

urlpatterns = [
    path('', indexView.as_view(), name='about')
]

contact/urls.py
from django.urls import path,include
from django.contrib import admin
from . import views

app_name='app_contact'
urlpatterns=[
    path('', views.index, name='contact'),
]

projects/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app_projects'

urlpatterns = [
    path('page-<int:page>/', views.indexView.as_view(), name='projects_page'),
    path('category-<str:category>/',
         views.indexView.as_view(), name='projects_category'),
    path('', views.indexView.as_view(), name='projects'),
    path('detail-<slug:slug>', views.detailProjectView.as_view(),
         name='detail_ProjectView'),
    path('report_project/<slug:proyek_slug>/',
         views.report_project, name='report_project'),
]

services/urls.py
from django.urls import path
from django.contrib import admin
from .views import indexView

app_name = 'app_services'

urlpatterns = [
    path('', indexView.as_view(), name='services')
]

skill/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app_skill'
urlpatterns = [
    path('', views.index, name='skill'),
]

templates/snippets/contain-menu.html
{% load static %}
<nav class="sidebar">
  <header class="logo">
    <span class="image"> <img src="{% static 'img/logo.png' %}" alt="logoxx" /></span>
    <span class="name">Achmad Irfan Afandi</span>
  </header>
  <!-- <div class="toggles"><i class="bx bxs-right-arrow toggle"></i></div> -->

  <!-- <div class="icon"> -->
  <div class="icon-social">
    <a href="https://www.linkedin.com/in/achmad-irfan-afandi-9661131a6/">
      <i class="bi bi-linkedin bi-lg custom-icon"></i>
    </a>
    <a href="https://github.com/achmad-irfan">
      <i class="bi bi-github bi-lg custom-icon"></i>
    </a>
    <a href="https://www.facebook.com/achmad.irfan.754">
      <i class="bi bi-facebook bi-lg custom-icon"></i>
    </a>
    <a href="https://www.facebook.com/achmad.irfan.754">
      <i class="bi bi-twitter bi-lg custom-icon"></i>
    </a>
    <a href="https://www.facebook.com/achmad.irfan.754">
      <i class="bi bi-instagram bi-lg custom-icon"></i>
    </a>
  </div>
  <!-- </div> -->

  <div class="menu">
    <a href="/">
      <div class="menu-link">
        <i class="bx bx-home"></i>
        <div class="contentMenu">HOME</div>
      </div>
    </a>

    <a href="{% url 'app_about:about' %}">
      <div class="menu-link">
        <i class="bi bi-file-earmark-person"></i>
        <div class="contentMenu">ABOUT</div>
      </div>
    </a>

    <a href="{% url 'app_education:education' %}">
      <div class="menu-link">
        <i class="bx bxs-graduation"></i>
        <div class="contentMenu">EDUCATION</div>
      </div>
    </a>

    <a href="{% url 'app_skill:skill' %}">
      <div class="menu-link">
        <i class="bx bx-wrench"></i>
        <div class="contentMenu">SKILL</div>
      </div>
    </a>

    <a href="{% url 'app_projects:projects' %}">
      <div class="menu-link">
        <i class="bx bx-building"></i>
        <div class="contentMenu">PROJECTS</div>
      </div>
    </a>

    <a href="{% url 'app_services:services' %}">
      <div class="menu-link">
        <i class="bx bx-support"></i>
        <div class="contentMenu">SERVICES</div>
      </div>
    </a>

    <a href="{% url 'app_contact:contact' %}">
      <div class="menu-link">
        <i class="bx bxs-contact"></i>
        <div class="contentMenu">CONTACT</div>
      </div>
    </a>
  </div>
</nav>

templates/snippets/form.html
<div class="form">
  <form method="post">{% csrf_token %} {{projectfrom}}</form>
</div>

templates/snippets/main_css.html
{% load static %} <link rel="stylesheet" type="text/css" href="{% static "css\styles.css" %}" />